# Generated by Django 2.1.1 on 2018-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_auto_20180918_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/profile'),
        ),
    ]
