# Generated by Django 2.1 on 2018-08-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product name', help_text='Enter your Product Title', max_length=200)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=9, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=9)),
                ('sortDec', models.TextField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='productThm')),
                ('is_Feature', models.BooleanField(default=True)),
                ('is_newAriavle', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='ecommarce.Category')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(blank=True, upload_to='productGallery')),
                ('image3', models.ImageField(blank=True, upload_to='productGallery')),
                ('image4', models.ImageField(blank=True, upload_to='productGallery')),
                ('image5', models.ImageField(blank=True, upload_to='productGallery')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommarce.ProductBasic')),
            ],
        ),
    ]
