# Generated by Django 2.1 on 2018-09-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mainCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommarce.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/thumbnail'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/Gallery'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/Gallery'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image4',
            field=models.ImageField(blank=True, upload_to='products/Gallery'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image5',
            field=models.ImageField(blank=True, upload_to='products/Gallery'),
        ),
    ]
