# Generated by Django 2.1 on 2018-09-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0003_auto_20180913_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasic',
            name='is_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productbasic',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='category',
            field=models.ManyToManyField(to='ecommarce.SubCategory'),
        ),
    ]
