# Generated by Django 2.1 on 2018-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0004_auto_20180913_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasic',
            name='name',
            field=models.CharField(help_text='Enter your Product Title', max_length=200),
        ),
    ]
