# Generated by Django 2.1.1 on 2018-09-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0007_auto_20180915_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image5',
        ),
    ]
