# Generated by Django 2.1.1 on 2018-09-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0009_auto_20180916_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbasic',
            name='category',
        ),
    ]
