# Generated by Django 2.1.1 on 2018-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0011_productbasic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasic',
            name='image',
            field=models.ImageField(blank=True, height_field=440, upload_to='products/thumbnail', width_field=640),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='unit',
            field=models.CharField(help_text='Enter unity deviate by comma', max_length=200),
        ),
    ]
