# Generated by Django 2.1.1 on 2018-09-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0012_auto_20180917_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasic',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/thumbnail'),
        ),
    ]
