# Generated by Django 2.1.1 on 2018-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0014_remove_order_delivery_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Enter Title Text', max_length=250)),
                ('sortDis', models.TextField()),
                ('image_file', models.ImageField(null=True, upload_to='Slider/image')),
                ('buttonText', models.CharField(help_text='button title text', max_length=100)),
                ('buttonUrl', models.CharField(help_text='Url', max_length=250)),
            ],
        ),
    ]
