# Generated by Django 2.1.1 on 2018-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0016_auto_20180923_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_status',
            new_name='is_confirm',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_Status',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coustomer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_Address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quentity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1, help_text='Enter your Delivery Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='dhaka', help_text='Enter Your Email ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_onprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='sam', help_text='Enter Your Fullname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='01', help_text='Enter Your phone ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
