# Generated by Django 2.1.1 on 2018-09-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0017_auto_20180923_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='quentity',
        ),
    ]
