# Generated by Django 2.1.1 on 2018-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0019_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasic',
            name='is_out_stock',
            field=models.BooleanField(default=False),
        ),
    ]
