# Generated by Django 2.1.1 on 2018-09-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0022_auto_20180926_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasic',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
