# Generated by Django 2.1.1 on 2018-09-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0024_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('o', 'Office Pick'), ('h', 'Home Delivery')], default=None, max_length=1, null=True),
        ),
    ]
