# Generated by Django 2.1.1 on 2018-09-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0025_auto_20180927_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
