# Generated by Django 2.1.1 on 2018-09-27 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0028_auto_20180927_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter your Area name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Enter your Delivery Address', max_length=250),
        ),
    ]
