# Generated by Django 2.1.1 on 2018-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0030_remove_order_is_on_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_Method',
            field=models.CharField(choices=[('o', 'Office Pick'), ('h', 'Home Delivery')], default=None, max_length=1),
        ),
    ]
