# Generated by Django 2.1.1 on 2018-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0032_auto_20180927_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspiringRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=155)),
                ('remarks', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='inspiring/author/img')),
                ('des', models.CharField(max_length=255)),
                ('fb', models.CharField(max_length=255)),
                ('twi', models.CharField(max_length=255)),
                ('sky', models.CharField(max_length=255)),
            ],
        ),
    ]
