# Generated by Django 2.1.1 on 2018-10-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0033_inspiringremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiringremark',
            name='fb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspiringremark',
            name='sky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspiringremark',
            name='twi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
