# Generated by Django 2.1.1 on 2018-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0034_auto_20181003_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiringremark',
            name='activ',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspiringremark',
            name='is_in_font',
            field=models.BooleanField(default=True),
        ),
    ]
