# Generated by Django 2.1.1 on 2018-10-03 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0036_auto_20181003_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiringremark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
