# Generated by Django 2.1.1 on 2018-10-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0038_auto_20181003_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Offer/img')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommarce.ProductBasic')),
            ],
        ),
    ]
